### ISSUE TITLE
File formats and new 2.0 OS for Pa4X

### ISSUE THREAD

**Issue by ChinaWhite77** [Polprzewodnikowy/KorgPackage#1]
Any idea as to why the format of the boot image is different in Pa600 as opposed to Pa4X? Meaning in the Pa600 OS the boot image is an PPM which can be viewed and in the Pa4X the extension is still PPM, but it can't be viewed and on inspection it missed the magic number and size... is it compressed or something? Also, the new Pa4X OS 2 is split into 6 parts, can your app be modified to work with this new OS as well? Is it still the same format, but split? Thanks!

**Comment by Polprzewodnikowy** [comment]
Most Pa4X OS packages are encrypted so that's why you can't just view/edit them. About split images - you can just join them together in hex editor or whatever method you can find. But I'd say it's pretty useless because of encryption. And yes, I'm still not able to decrypt any file.

**Comment by musiccankill** [comment]
Also i would like to add that the new format (upd for pa4x and pkg for 700/1000) seems to have a way different validation system which could even be asymmetric key encryption...
If that is the case , it will never be open again except if there will be a key leak from a person working for Korg (high unlikely)...

**Comment by sercan191** [comment]
hello I'll have a question, how can I unlock korg pa 500 ram?

**Comment by sercan191** [comment]
i need so much to solve it

**Comment by musiccankill** [comment]
@sercan191 Pa500 has no ram.The IC's soldered on the mainboard are rom ones...

**Comment by sercan191** [comment]
How to install pcm file

**Comment by sercan191** [comment]
I can't get sample sound from outside

**Comment by sercan191** [comment]
There must be a way

**Comment by musiccankill** [comment]
@sercan191 The only way to change the factory library is to remove the rom IC's, read their contents , analyze them to find out how it works, recreate the way it works, write new compatible flash chips if there are any and resolder them....So yes the short answer is that it is not possible...

**Comment by Polprzewodnikowy** [comment]
Well this is getting ridiculous so I need to close this issue.
I'm still considering closing this project entirely because I'm not interested in expanding it any more.
You can fork it and try fixing it yourself.

**Comment by mehranmasoumi** [comment]
Hi.

Which version of korg pa4x os opens for korgpacage?
