### ISSUE TITLE
Editing Sets

### ISSUE THREAD

**Issue by narrsam** [Polprzewodnikowy/KorgPackage#3]
Hi,

Is there any possibility to add an editor for the .set package produced by Korg PA series?
If not, any suggestion of where to start, how to decipher the file formats or what tools can be used is much appreciated.

Thanks,
Sam

**Comment by musiccankill** [comment]
There is a set management utility called korg pa manager and does a pretty good job not even for managing sets but even merging them easily (along with a lot of other useful features).

**Comment by narrsam** [comment]
I have it already, but I am trying to create a midi controller that can
read the sets and reflect them in its interface so I was wondering how to
read the files to extract this information just like Korg PA Manager does.
