### ISSUE TITLE
korg pkg edite

### ISSUE THREAD

**Issue by jonel83** [Polprzewodnikowy/KorgPackage#4]
hello, I appreciate your work, I have encountered a problem with the software pkg edit i tried to open in windos a pkg korg pa 3x, to boot to a picture with my family, but it does not open my program, except for models 300, pa 600,900, pa. 1,000 and pa 4x, thank you and I expect a response

**Comment by Polprzewodnikowy** [comment]
Korg Pa3X uses older and different format from the Linux based keyboards so it's unsupported. No surprise it's not working, giving the fact that I specifically wrote the compatibility list.

**Comment by jonel83** [comment]
thank you for your courtesy of answering but I hope you will not be mistaken in compatible models of you mentioned and korg pa 3x, I apologize if I misunderstood, as an informative note there is some way with software editing software...

**Comment by abuzead811** [comment]
My friend i need you for great business 
Can you text me on my whatsapp or any chat app?
+962788798345
Its about korgpkg
Private business

**Comment by KyuubiMusic** [comment]
Olá amigo venho pedir ajuda para saber se pode me mandar todos os programas que usa para editar arquivos PKG KORG, muito obrigado, e parabéns pelo ótimo trabalho, me chamo Kyubi Music do Brasil, comprei o Sample Editor pro Pa600 a muitos anos atrás por $50,00 de vc caso vc seja o criado do mesmo
